package com.fish.live.database.db;


import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

//    private final DaoConfig exchangeOilFriendDaoConfig;
//    private final DaoConfig searchLinesHistoryBeanDaoConfig;
//    private final DaoConfig searchStationHistoryBeanDaoConfig;

//    private final ExchangeOilFriendDao exchangeOilFriendDao;
//    private final SearchLinesHistoryBeanDao searchLinesHistoryBeanDao;
//    private final SearchStationHistoryBeanDao searchStationHistoryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

//        exchangeOilFriendDaoConfig = daoConfigMap.get(ExchangeOilFriendDao.class).clone();
//        exchangeOilFriendDaoConfig.initIdentityScope(type);
//
//        searchLinesHistoryBeanDaoConfig = daoConfigMap.get(SearchLinesHistoryBeanDao.class).clone();
//        searchLinesHistoryBeanDaoConfig.initIdentityScope(type);
//
//        searchStationHistoryBeanDaoConfig = daoConfigMap.get(SearchStationHistoryBeanDao.class).clone();
//        searchStationHistoryBeanDaoConfig.initIdentityScope(type);

//        exchangeOilFriendDao = new ExchangeOilFriendDao(exchangeOilFriendDaoConfig, this);
//        searchLinesHistoryBeanDao = new SearchLinesHistoryBeanDao(searchLinesHistoryBeanDaoConfig, this);
//        searchStationHistoryBeanDao = new SearchStationHistoryBeanDao(searchStationHistoryBeanDaoConfig, this);
//
//        registerDao(ExchangeOilFriend.class, exchangeOilFriendDao);
//        registerDao(SearchLinesHistoryBean.class, searchLinesHistoryBeanDao);
//        registerDao(SearchStationHistoryBean.class, searchStationHistoryBeanDao);
    }
    
    public void clear() {
//        exchangeOilFriendDaoConfig.clearIdentityScope();
//        searchLinesHistoryBeanDaoConfig.clearIdentityScope();
//        searchStationHistoryBeanDaoConfig.clearIdentityScope();
    }
//
//    public ExchangeOilFriendDao getExchangeOilFriendDao() {
//        return exchangeOilFriendDao;
//    }
//
//    public SearchLinesHistoryBeanDao getSearchLinesHistoryBeanDao() {
//        return searchLinesHistoryBeanDao;
//    }
//
//    public SearchStationHistoryBeanDao getSearchStationHistoryBeanDao() {
//        return searchStationHistoryBeanDao;
//    }

}
